name: Publish Quarto Website

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Python packages
      - run: |
          python -m pip install --upgrade pip
          pip install jupyter pyyaml polars

      # Install Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # Render site
      - run: quarto render

      # Deploy to gh-pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
